backend:
  name: github
  repo: lallhar/SQUARESPACES

media_folder: "src/assets/images"

collections:
  - name: squarespace
    label: squarespacesite
    folder: src/pages/index.js
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }